name:    sbsvc
version: "0.0.0"

dependencies:
- base
- yesod-core
- text
- smartbook
- bytestring
- containers
- aeson

library:
  source-dirs: src

# Runnable executable for our application
executables:
  sbsvc:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sbsvc
